import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman Lahariya
 */
public class Edit_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Edit_Customer
     */
    public Edit_Customer() {
        initComponents();
    }
    
    int cid;
    void clearAll()
    {
        txt_Fname.setText("");
        txt_Lname.setText("");
        txt_FatherName.setText("");
        cb_city.setSelectedIndex(0);
        txt_Address.setText("");
        txt_Phno.setText("");
        cb_Name.setSelectedIndex(0);
    }
      
    void fillCustomer()
    {
        cb_Name.removeAllItems();
        cb_Name.addItem("Select");
        //String cname;
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select fullname from customer order by fname";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {   
                    cb_Name.addItem(rs.getString("fullname"));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }
    
    void fillCity()
    {
        cb_city.removeAllItems();
        cb_city.addItem("Select");
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from city order by cname";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    cb_city.addItem(rs.getString("cname"));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Fname = new javax.swing.JTextField();
        txt_Lname = new javax.swing.JTextField();
        txt_FatherName = new javax.swing.JTextField();
        txt_Address = new javax.swing.JTextField();
        bt_Save = new javax.swing.JButton();
        cmd_Back = new javax.swing.JButton();
        bt_Clear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb_city = new javax.swing.JComboBox<>();
        lbl_AddCity = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Phno = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_Name = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Customer");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel3.setText("Edit Customer Details");

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel4.setText("Father's Name:");

        jLabel5.setText("Address:");

        bt_Save.setText("Save");
        bt_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SaveActionPerformed(evt);
            }
        });

        cmd_Back.setText("Back");
        cmd_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_BackActionPerformed(evt);
            }
        });

        bt_Clear.setText("Clear");

        jLabel6.setText("City:");

        cb_city.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        lbl_AddCity.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lbl_AddCity.setForeground(new java.awt.Color(204, 0, 0));
        lbl_AddCity.setText("[+]");
        lbl_AddCity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddCityMouseClicked(evt);
            }
        });

        jLabel7.setText("Phone No:");

        jLabel8.setText("Full Name:");

        cb_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        cb_Name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_NameFocusLost(evt);
            }
        });
        cb_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_AddCity)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Address)
                            .addComponent(txt_Lname)
                            .addComponent(cb_city, 0, 140, Short.MAX_VALUE)
                            .addComponent(txt_Fname)
                            .addComponent(cb_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(bt_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(bt_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Phno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cmd_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_AddCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Phno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Save)
                    .addComponent(cmd_Back)
                    .addComponent(bt_Clear))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SaveActionPerformed
        // TODO add your handling code here:

        // Validation
        if(txt_Fname.getText().equals("") || txt_Lname.getText().equals("") || txt_FatherName.getText().equals("") || cb_city.getSelectedItem().equals("Select") || txt_Address.getText().equals("") || txt_Phno.getText().equals("") )
        {
            JOptionPane.showMessageDialog(this,"Please select/enter data in all fields !");
        }
        else
        {
            try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                int id = mf.cid();
                String fullname = txt_Fname.getText()+" "+txt_Lname.getText();
                String query = "update customer set fname = '"+ txt_Fname.getText() +"',lname = '"+ txt_Lname.getText() +"',fathername = '"+ txt_FatherName.getText() +"',address = '"+ txt_Address.getText() +"',city = '"+ cb_city.getSelectedItem() +"',phoneno = '"+ txt_Phno.getText() +"',fullname = '"+fullname+"' where cid = "+cid+"";
                int r = stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Customer details updated !");
                clearAll();
                fillCustomer();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_bt_SaveActionPerformed

    private void cmd_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmd_BackActionPerformed

    private void lbl_AddCityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddCityMouseClicked
        // TODO add your handling code here:
        String cname = "";
        cname = JOptionPane.showInputDialog("Enter City Name");
        if(!cname.equals(""))
        {
            try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Insert into city values('"+ cname +"')";
                int r = stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"City added!");
                fillCity();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_lbl_AddCityMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        fillCity();
        fillCustomer();
    }//GEN-LAST:event_formWindowOpened

    private void cb_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cb_NameActionPerformed

    private void cb_NameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_NameFocusLost
        // TODO add your handling code here:
        String cname = "";
        cname = cb_Name.getSelectedItem().toString();
        if(cname == "Select" || cname == "")
        {
            txt_Fname.setText("");
            txt_Lname.setText("");
            txt_FatherName.setText("");
            txt_Address.setText("");
            cb_city.setSelectedIndex(0);
            txt_Phno.setText("");
        }
        else
        {
            MyFunctions mf = new MyFunctions();
            cid = mf.retreive_cid(cname);
            try
            {
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from customer where cid = "+cid+"";
                ResultSet rs = stmt.executeQuery(query);
                rs.next();
                   
                    txt_Fname.setText(rs.getString("fname"));
                    txt_Lname.setText(rs.getString("lname"));
                    txt_FatherName.setText(rs.getString("fathername"));
                    txt_Address.setText(rs.getString("address"));
                    cb_city.setSelectedItem(rs.getString("city"));
                    txt_Phno.setText(rs.getString("phoneno"));
                 
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_cb_NameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Clear;
    private javax.swing.JButton bt_Save;
    private javax.swing.JComboBox<String> cb_Name;
    private javax.swing.JComboBox<String> cb_city;
    private javax.swing.JButton cmd_Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AddCity;
    private javax.swing.JTextField txt_Address;
    private javax.swing.JTextField txt_FatherName;
    private javax.swing.JTextField txt_Fname;
    private javax.swing.JTextField txt_Lname;
    private javax.swing.JTextField txt_Phno;
    // End of variables declaration//GEN-END:variables
}
