import java.util.Date;
import java.sql.*;
import java.lang.String;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman Lahariya
 */
public class Mortgage_Entry extends javax.swing.JFrame {

    /**
     * Creates new form Mortgage_Entry
     */
    public Mortgage_Entry() {
        initComponents();
    }
    
    void fillCustomer()
    {
        cb_customer.removeAllItems();
        cb_customer.addItem("Select");
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select fullname from customer order by fname";
                ResultSet rs = stmt.executeQuery(query);
                
                while(rs.next())
                {   
                    cb_customer.addItem(rs.getString("fullname"));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }
    
    void fillAurnament()
    {
        cb_ornament.removeAllItems();
        cb_ornament.addItem("Select");
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from ornament_type order by name";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    cb_ornament.addItem(rs.getString("name"));                 //OR SEE THE SAME CODE BUT WITH DIFF LOGIC IN CUSTOMER_ACCOUNT FORM
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }
    void fillJewelleryType()
    {
        cb_Jewellery.removeAllItems();
        cb_Jewellery.addItem("Select");
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from jewellery_type order by name";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    cb_Jewellery.addItem(rs.getString("name"));                 //OR SEE THE SAME CODE BUT WITH DIFF LOGIC IN CUSTOMER_ACCOUNT FORM
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }
    void clearAll()
    {
        Date date = new Date();
        jDateChooser1.setDate(date);
        txt_Receipt.setText("");
        cb_customer.setSelectedIndex(0);
        txt_FatherName.setText("");
        cb_Jewellery.setSelectedItem(0);
        cb_ornament.setSelectedItem(0);
        txt_Weight.setText("");
        txt_Purity.setText("");
        txt_OtherInfo.setText("-");
        txt_Amt_Given.setText("");
        txt_InterestRate.setText("1.5");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_Weight = new javax.swing.JTextField();
        txt_Purity = new javax.swing.JTextField();
        txt_OtherInfo = new javax.swing.JTextField();
        cb_Jewellery = new javax.swing.JComboBox<>();
        cb_ornament = new javax.swing.JComboBox<>();
        lbl_AddAurnament = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_AddJewellery = new javax.swing.JLabel();
        txt_Receipt = new javax.swing.JTextField();
        txt_FatherName = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lbl_AddCustomer = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_Amt_Given = new javax.swing.JTextField();
        txt_InterestRate = new javax.swing.JTextField();
        cmd_Add = new javax.swing.JButton();
        cmd_Clear = new javax.swing.JButton();
        cmd_Back = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cb_customer = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mortgage Entry");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel3.setText("Mortage Entry");

        jLabel1.setText("Receipt No:");

        jLabel2.setText("Date:");

        jLabel4.setText("Customer Name:");

        jLabel5.setText("Father's Name:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jLabel6.setText("Jewellery Type:");

        jLabel7.setText("Ornament Type:");

        jLabel8.setText("Weight:");

        jLabel9.setText("Purity:");

        jLabel10.setText("Other Info:");

        cb_Jewellery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));

        cb_ornament.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Ring", "Necklace" }));

        lbl_AddAurnament.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lbl_AddAurnament.setForeground(new java.awt.Color(204, 0, 0));
        lbl_AddAurnament.setText("[+]");
        lbl_AddAurnament.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddAurnamentMouseClicked(evt);
            }
        });

        jLabel13.setText("%");

        jLabel15.setText("gm");

        lbl_AddJewellery.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lbl_AddJewellery.setForeground(new java.awt.Color(204, 0, 0));
        lbl_AddJewellery.setText("[+]");
        lbl_AddJewellery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddJewelleryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_OtherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_Purity, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cb_Jewellery, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_AddJewellery)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_AddAurnament))
                                    .addComponent(jLabel9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_ornament, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(cb_Jewellery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_ornament, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_AddAurnament, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_AddJewellery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Weight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Purity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_OtherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        txt_FatherName.setEditable(false);

        lbl_AddCustomer.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        lbl_AddCustomer.setForeground(new java.awt.Color(204, 0, 0));
        lbl_AddCustomer.setText("[+]");
        lbl_AddCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AddCustomerMouseClicked(evt);
            }
        });

        jLabel11.setText("Amount Given:");

        jLabel12.setText("Interest Rate:");

        cmd_Add.setText("Add");
        cmd_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_AddActionPerformed(evt);
            }
        });

        cmd_Clear.setText("Clear");
        cmd_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_ClearActionPerformed(evt);
            }
        });

        cmd_Back.setText("Back");
        cmd_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_BackActionPerformed(evt);
            }
        });

        jLabel14.setText("%");

        jLabel16.setText("Rs.");

        cb_customer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cb_customerFocusLost(evt);
            }
        });
        cb_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_customerActionPerformed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setText("Refresh");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(cmd_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(131, 131, 131)
                                .addComponent(cmd_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel11)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_Amt_Given, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(28, 28, 28)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(cmd_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(txt_InterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Receipt, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(cb_customer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_AddCustomer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_Receipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lbl_AddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(txt_Amt_Given, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_InterestRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmd_Back)
                        .addComponent(cmd_Clear)
                        .addComponent(cmd_Add)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_AddAurnamentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddAurnamentMouseClicked
        // TODO add your handling code here:
        String name = "";
        name = JOptionPane.showInputDialog("Enter Name of Aurnament");
        if(!name.equals(""))
        {
            try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Insert into ornament_type values('"+ name +"')";
                int r = stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Ornament Type Added!");
                fillAurnament();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_lbl_AddAurnamentMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        //MyFunctions my = new MyFunctions();
        //int billno = my.billNo();
        //txt_BillNo.setText(String.valueOf(billno));
        
        Date date = new Date();
        jDateChooser1.setDate(date);
        
        txt_InterestRate.setText("2.5");
        txt_OtherInfo.setText("-");
        
        fillCustomer();
        fillAurnament();
        fillJewelleryType();
    }//GEN-LAST:event_formWindowOpened

    private void lbl_AddCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddCustomerMouseClicked
        // TODO add your handling code here:
       Add_Customer ac = new Add_Customer();
       ac.show();
    }//GEN-LAST:event_lbl_AddCustomerMouseClicked

    private void cmd_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_ClearActionPerformed
        // TODO add your handling code here:
        clearAll();
    }//GEN-LAST:event_cmd_ClearActionPerformed

    private void cmd_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_AddActionPerformed
        // TODO add your handling code here:
        if(txt_Receipt.getText().equals("") || txt_Weight.getText().equals("") || txt_Purity.getText().equals("") || cb_customer.getSelectedItem().equals("Select") || txt_OtherInfo.getText().equals("") || cb_Jewellery.getSelectedItem().equals("Select") || cb_ornament.getSelectedItem().equals("Select") || txt_Amt_Given.getText().equals("") || txt_InterestRate.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please select/enter data in all fields !");
        }
        else
        {
            try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                int mid = mf.mid();
                int cid = mf.retreive_cid(cb_customer.getSelectedItem().toString());
                String entryDate;
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                entryDate = sdf.format(jDateChooser1.getDate());
                String query = "Insert into mortgage_entry values("+mid+","+cid+",'"+ txt_Receipt.getText() +"','"+ entryDate +"','"+ cb_Jewellery.getSelectedItem() +"','"+ cb_ornament.getSelectedItem() +"','"+ txt_Weight.getText() +"','"+ txt_Purity.getText() +"','"+ txt_OtherInfo.getText() +"','"+ txt_Amt_Given.getText() +"','"+ txt_InterestRate.getText() +"','Yet to Return')";
                int r = stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Details added !");
                int cnf = JOptionPane.showConfirmDialog(this,"Do you want to clear all the fields ?","Confirm",JOptionPane.YES_NO_OPTION);
                if(cnf == 0)
                {
                  clearAll();  
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_cmd_AddActionPerformed

    private void cb_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_customerActionPerformed
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_cb_customerActionPerformed

    private void cmd_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cmd_BackActionPerformed

    private void lbl_AddJewelleryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AddJewelleryMouseClicked
        // TODO add your handling code here:
        String name = "";
        name = JOptionPane.showInputDialog("Enter Type of Jewellery");
        if(!name.equals(""))
        {
            try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Insert into jewellery_type values('"+ name +"')";
                int r = stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(this,"Jewellery Type Added!");
                fillJewelleryType();
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_lbl_AddJewelleryMouseClicked

    private void cb_customerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_customerFocusLost
        // TODO add your handling code here:
         String name = cb_customer.getSelectedItem().toString();
        if(name == "Select")
        {
            txt_FatherName.setText("");
            JOptionPane.showMessageDialog(this,"Please select customer name!");
        }
        else
        {
            MyFunctions mf = new MyFunctions();
            int cid = mf.retreive_cid(name);
            try
            {
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select fathername from customer where cid = "+cid+" ";
                ResultSet rs1 = stmt.executeQuery(query);
                rs1.next();
                txt_FatherName.setText(rs1.getString("fathername"));
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
        }
    }//GEN-LAST:event_cb_customerFocusLost

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        fillCustomer();
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mortgage_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mortgage_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mortgage_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mortgage_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mortgage_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Jewellery;
    private javax.swing.JComboBox<String> cb_customer;
    private javax.swing.JComboBox<String> cb_ornament;
    private javax.swing.JButton cmd_Add;
    private javax.swing.JButton cmd_Back;
    private javax.swing.JButton cmd_Clear;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_AddAurnament;
    private javax.swing.JLabel lbl_AddCustomer;
    private javax.swing.JLabel lbl_AddJewellery;
    private javax.swing.JTextField txt_Amt_Given;
    private javax.swing.JTextField txt_FatherName;
    private javax.swing.JTextField txt_InterestRate;
    private javax.swing.JTextField txt_OtherInfo;
    private javax.swing.JTextField txt_Purity;
    private javax.swing.JTextField txt_Receipt;
    private javax.swing.JTextField txt_Weight;
    // End of variables declaration//GEN-END:variables
}
