
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charlie
 */
public class Remove_User extends javax.swing.JFrame {

    
    public Remove_User() {
        initComponents();
    }
     String Usertype;
     // Function to fill combo box user_type & user_name.
     void filldetails()
     {
        //String Usertype;
        Usertype = cb_UserType.getSelectedItem().toString();
        if(Usertype == "Select")
        {
            JOptionPane.showMessageDialog(this,"Please select valid user type...");
           // cb_UserType.requestFocus();
            cb_UserName.removeAllItems();
            cb_UserName.addItem("Select");
        }
        else
        {
            try
            {
                cb_UserName.removeAllItems();
                cb_UserName.addItem("Select");
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select uname from users where utype = '"+Usertype+"'";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    cb_UserName.addItem(rs.getString("uname"));
                }
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_UserType = new javax.swing.JComboBox();
        bt_RemoveUser = new javax.swing.JButton();
        bt_Back = new javax.swing.JButton();
        cb_UserName = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remove User");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel3.setText("Remove User");

        jLabel1.setText("User Type:");

        jLabel2.setText("User Name:");

        cb_UserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Admin", "Employee" }));
        cb_UserType.setName(""); // NOI18N
        cb_UserType.setNextFocusableComponent(bt_Back);
        cb_UserType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_UserTypeItemStateChanged(evt);
            }
        });

        bt_RemoveUser.setText("Remove User");
        bt_RemoveUser.setToolTipText("Removes details from database");
        bt_RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RemoveUserActionPerformed(evt);
            }
        });

        bt_Back.setText("Back");
        bt_Back.setToolTipText("Takes you back to prev form");
        bt_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_BackActionPerformed(evt);
            }
        });

        cb_UserName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cb_UserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cb_UserNameFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addComponent(cb_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_RemoveUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_UserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_RemoveUser)
                    .addComponent(bt_Back))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RemoveUserActionPerformed
        // TODO add your handling code here:
        String Username;
        Username = cb_UserName.getSelectedItem().toString();
        if(Username == "Select")
        {
            JOptionPane.showMessageDialog(this,"Please select user name...");
        }
        else
        {
          int cnf = JOptionPane.showConfirmDialog(null,"Do you really want to revome user "+ Username +" !","Confirm",JOptionPane.YES_NO_OPTION);
          if(cnf == 0)
          {
            try
            {
                int cnt = 2;
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                if(Usertype.equals("Admin"))
                {
                    String query1 = "Select count(*) from users where utype = '"+Usertype+"'";
                    ResultSet rs = stmt.executeQuery(query1);
                    while(rs.next())
                    {
                        cnt = rs.getInt(1);
                    }  
                }
                
                if(cnt <=1)
                {
                    JOptionPane.showMessageDialog(this,"You can not delete the last remaining Admin!");
                }
                else
                {
                    String query2 = "Delete from users where uname = '"+Username+"'";
                    int r = stmt.executeUpdate(query2);
                    JOptionPane.showMessageDialog(this,"User " +Username+" removed...");
                }
                
                filldetails();
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, e);
            }
          }
        }
    }//GEN-LAST:event_bt_RemoveUserActionPerformed

    private void bt_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_BackActionPerformed

    private void cb_UserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cb_UserNameFocusGained
        // TODO add your handling code here:
        
        Usertype = cb_UserType.getSelectedItem().toString();
        if(Usertype == "Select")
        {
            JOptionPane.showMessageDialog(this,"Please select valid user type...");
            cb_UserName.setFocusable(false);
            cb_UserName.removeAllItems();
            cb_UserName.addItem("Select");
        }
    }//GEN-LAST:event_cb_UserNameFocusGained

    private void cb_UserTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_UserTypeItemStateChanged
        // TODO add your handling code here:
            filldetails();
    }//GEN-LAST:event_cb_UserTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Back;
    private javax.swing.JButton bt_RemoveUser;
    private javax.swing.JComboBox cb_UserName;
    private javax.swing.JComboBox cb_UserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
