import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman Lahariya
 */
public class Search_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Search_Customer
     */
    public Search_Customer() {
        initComponents();
    }
    
     void clear()
    {
        int rows = 0;
        DefaultTableModel model_interest=(DefaultTableModel)table_Customer.getModel();
        rows = model_interest.getRowCount();
        if(rows > 0)
        {
            for(int i=0; i<rows; i++)
            {
                model_interest.removeRow(0);
            }
        }
    }
    void fillCustomer()
    {
        cb_Select.removeAllItems();
        cb_Select.addItem("Select");
        String cname;
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from customer order by fname";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {   
                    cname = rs.getString("fname")+" " + rs.getString("lname");
                    cb_Select.addItem(cname);
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }
    
    void fillCity()
    {
        cb_Select.removeAllItems();
        cb_Select.addItem("Select");
        try
            {
                MyFunctions mf = new MyFunctions();
                Connection cn = mf.myConnection();
                Statement stmt = cn.createStatement();
                String query = "Select * from city order by cname";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next())
                {
                    cb_Select.addItem(rs.getString("cname"));
                }
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel_SearchBy = new javax.swing.JPanel();
        rb_Cust_Name = new javax.swing.JRadioButton();
        rd_All = new javax.swing.JRadioButton();
        rb_City = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Customer = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_Select = new javax.swing.JLabel();
        cb_Select = new javax.swing.JComboBox();
        bt_Search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Customer");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        jLabel3.setText("Search Customer");

        jPanel_SearchBy.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Record by :"));

        buttonGroup1.add(rb_Cust_Name);
        rb_Cust_Name.setText("Customer Name");
        rb_Cust_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_Cust_NameActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd_All);
        rd_All.setText("View All");
        rd_All.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_AllActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_City);
        rb_City.setText("City");
        rb_City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_CityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_SearchByLayout = new javax.swing.GroupLayout(jPanel_SearchBy);
        jPanel_SearchBy.setLayout(jPanel_SearchByLayout);
        jPanel_SearchByLayout.setHorizontalGroup(
            jPanel_SearchByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SearchByLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb_Cust_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(rb_City, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rd_All, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_SearchByLayout.setVerticalGroup(
            jPanel_SearchByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_SearchByLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_SearchByLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_Cust_Name)
                    .addComponent(rd_All)
                    .addComponent(rb_City))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        table_Customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Father's Name", "Address", "City", "Phone No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_Customer);

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl_Select.setText("Select Customer Name:");

        cb_Select.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        cb_Select.setEnabled(false);
        cb_Select.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_SelectMouseClicked(evt);
            }
        });

        bt_Search.setText("Search");
        bt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel_SearchBy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cb_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_SearchBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Select)
                            .addComponent(cb_Select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_Search))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_Cust_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_Cust_NameActionPerformed
        // TODO add your handling code here:
        clear();
        lbl_Select.setText("Select Customer Name:");
        cb_Select.enable(true);
        cb_Select.setSelectedIndex(0);
        fillCustomer();
    }//GEN-LAST:event_rb_Cust_NameActionPerformed

    private void rd_AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_AllActionPerformed
        // TODO add your handling code here:
        clear();
        cb_Select.enable(false);
        cb_Select.setSelectedIndex(0);
        bt_Search.doClick();
    }//GEN-LAST:event_rd_AllActionPerformed

    private void rb_CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_CityActionPerformed
        // TODO add your handling code here:
        clear();
        lbl_Select.setText("Select City:");
        cb_Select.enable(true);
        cb_Select.setSelectedIndex(0);
        fillCity();
    }//GEN-LAST:event_rb_CityActionPerformed

    private void cb_SelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_SelectMouseClicked
        // TODO add your handling code here:

        // Clearing table content
        DefaultTableModel model=(DefaultTableModel)table_Customer.getModel();
        int rows=model.getRowCount();
        if(rows > 0)
        {
            for(int i=0; i<rows; i++)
            {
                model.removeRow(0);
            }
        }
    }//GEN-LAST:event_cb_SelectMouseClicked

    private void bt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SearchActionPerformed
        // TODO add your handling code here:
        try
        {
            clear();
            String query =null;
            MyFunctions mf = new MyFunctions();
            Connection cn = mf.myConnection();
            Statement stmt1 = cn.createStatement();
            DefaultTableModel model_debit = (DefaultTableModel) table_Customer.getModel();
            
            if(rb_Cust_Name.isSelected())
            {
                String name = cb_Select.getSelectedItem().toString();
                //MyFunctions mf = new MyFunctions();
                int cid = mf.retreive_cid(name);
                query = "Select * from customer where cid = '"+ cid +"'";
            }

            else if(rb_City.isSelected())
            {
                    query = "Select * from customer where city = '"+ cb_Select.getSelectedItem().toString() +"'  ";
            }
            else
            {
                query = "Select * from customer";
            }

            if(query!=null)
            {
                ResultSet rs1 = stmt1.executeQuery(query);
                boolean noRecord = true;
                while(rs1.next())
                {
                    noRecord = false;
                    String name = rs1.getString("fullname");
                    String fname = rs1.getString("fathername");
                    String address = rs1.getString("address");
                    String city = rs1.getString("city");
                    String phno = rs1.getString("phoneno");
                    model_debit.addRow(new Object[]{name,fname,address,city,phno});
                }
                if(noRecord)
                {
                    JOptionPane.showMessageDialog(this,"No Record found !");
                }
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_bt_SearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Search;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb_Select;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel_SearchBy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Select;
    private javax.swing.JRadioButton rb_City;
    private javax.swing.JRadioButton rb_Cust_Name;
    private javax.swing.JRadioButton rd_All;
    private javax.swing.JTable table_Customer;
    // End of variables declaration//GEN-END:variables
}
